### PR TITLE
Remove dependency on HOME env var

### LINKED ISSUE #102: Windows distro uses HOME env var which is commonly not available
The HOME env var is not always set in a windows environments, causing config-ssh to fail not knowing where to put the private key.

### PR DESCRIPTION
**Pull request by cmoog**
Closes #102

### CODE REVIEW

**Comment by wbobeirne** [comment]
Tagging in @creack as both a Go wizard, and a Windows user

**Comment by cmoog** [comment]
> Tagging in @creack as both a Go wizard, and a Windows user

Sounds good. It should be noted that I am _definitely_ _not_ a windows user.

**Comment by creack** [comment]
For the records, I am not either!, But I'll look into it :)

File: internal/cmd/configssh.go [hunk 1]
```diff
@@ -52,11 +52,14 @@ func configSSH(configpath *string, remove *bool) func(cmd *cobra.Command, _ []st
 		ctx, cancel := context.WithCancel(context.Background())
 		defer cancel()
 
+		usr, err := user.Current()
```
Comment (creack) [inline internal/cmd/configssh.go:55]: That is going to be a problem on some systems and will prevent us from shipping a static binaries.
It has been a while, I'm looking into this to see the extent, it might have improved.

Comment (creack) [reply internal/cmd/configssh.go:55]: Alright, I didn't see we were using it before already.
I checked and at least in go1.15, it does work without cgo! Which is quite neat.

Comment (creack) [reply internal/cmd/configssh.go:55]: Tested with and without cgo, and tested on windows, works as expected.
Slight note on windows, the path output has double `\`.
window ssh-config coder-cli

Comment (cmoog) [reply internal/cmd/configssh.go:55]: Pushed a fix that resolves the double `\` (straight to master by accident 😰 ).
