### PR TITLE
Fix coder sh freeze

### LINKED ISSUE #40: Coder sh freezes
I just had this happen for the first time ever, ~20 minutes after updating to the wsep version. After returning to my terminal after a bit of idling, it's completely unresponsive. No inputs are registered, ctrl+c / ctrl+d won't escape, I had to close the terminal and reconnect.

The old wush implementation would just kick me back out to my local session periodically, so I assume the disconnect that is happening isn't being gracefully treated with the wsep implementation.

### PR DESCRIPTION
**Pull request by cmoog**
Fixes #40

### CODE REVIEW

File: cmd/coder/shell.go [hunk 1]
```diff
@@ -142,10 +145,26 @@ func runCommand(ctx context.Context, envName string, command string, args []stri
...
+		}
 	}()
-	go io.Copy(os.Stdout, process.Stdout())
-	go io.Copy(os.Stderr, process.Stderr())
-
-	return process.Wait()
+	go func() {
+		_, err := io.Copy(os.Stdout, process.Stdout())
+		if err != nil {
+			cancel()
```
Comment (ammario) [inline cmd/coder/shell.go:156]: nitpick: If one of these closes both do... It's fair to just defer cancel() at the top of both

Comment (cmoog) [reply cmd/coder/shell.go:156]: I don't think it's good to depend on that behavior though...
